### ISSUE TITLE
ham adapter insecure mode

### ISSUE THREAD

**Issue by fighterzg6** [ioBroker/ioBroker.ham#14]
hi it is possible thats iobroker.ham starts in insecure mode??
i need this for alexa

**Comment by Apollon77** [comment]
Do you have more Details in „insecure mode“? What exactly is the issue with Alexa?

**Comment by fighterzg6** [comment]
The plugin allows you to view and control some types of Homebridge accessories from your web browser.

To enable accessory control you must be running Homebridge in insecure mode:

homebridge -I
Insecure mode, as it's name suggests, is not secure. Anyone with network access to your Homebridge server port and pin will be able to control your accessories. Unless exposing the Homebridge port to the internet, this will generally not be a problem as access will be limited to people already on your local network. Remote access via a home hub (Apple TV, iPad, HomePod etc.) will still be secure. Enable at your own risk.

my plugin for home bridge need this, 
my global homebridge starts with the command homebridge -I, then all plugins can access the data.

How can I adjust this in the adapter that he calls the homebridge with this option

**Comment by Apollon77** [comment]
Ok, need to check this. It is not about „starting with the parameter“ but setting that flag internally correctly.

**Comment by fighterzg6** [comment]
OK thanks! if that works, that would be absolutely the bang

**Comment by fighterzg6** [comment]
In deutsch würde das auch funktionieren

**Comment by fighterzg6** [comment]
hallo, gibt es schon etwas neues??

**Comment by Apollon77** [comment]
Ja das ich viele Themen habe und schauen muss wann was kommt. Bitte abwarten

**Comment by Apollon77** [comment]
Bitte 1.0.0 vom Github testen. Github install, am besten noch ein "iobroker upload ham" hinterher und dann neu starten. Instanzkonfig sollte eine neue Einstellung für Aktivieren des Insecure Mode haben. 

Bitte Testfeedback geben

**Comment by fighterzg6** [comment]
wede ich morgen gleich teste. mir ist heute die sd karte im raspberry zerbrochen. morgen hab ich das system am laufen. vielen dank im voraus

**Comment by fighterzg6** [comment]
2018-12-05 17:57:47.933 - info: ham.0 terminating
2018-12-05 17:57:47.953 - error: Caught by controller[0]: Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
2018-12-05 17:57:47.954 - error: Caught by controller[0]: was compiled against a different Node.js version using
2018-12-05 17:57:47.954 - error: Caught by controller[0]: NODE_MODULE_VERSION 67. This version of Node.js requires
2018-12-05 17:57:47.954 - error: Caught by controller[0]: NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
2018-12-05 17:57:47.954 - error: Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
2018-12-05 17:57:47.954 - error: Caught by controller[0]: at Object.Module._extensions..node (module.js:681:18)
2018-12-05 17:57:47.954 - error: Caught by controller[0]: at Module.load (module.js:565:32)
2018-12-05 17:57:47.954 - error: Caught by controller[0]: at tryModuleLoad (module.js:505:12)
2018-12-05 17:57:47.955 - error: Caught by controller[0]: at Function.Module._load (module.js:497:3)
2018-12-05 17:57:47.955 - error: Caught by controller[0]: at Function.Module._load (/opt/iobroker/node_modules/mock-require/index.js:29:22)
2018-12-05 17:57:47.955 - error: Caught by controller[0]: at Module.require (module.js:596:17)
2018-12-05 17:57:47.955 - error: Caught by controller[0]: at require (internal/module.js:11:18)
2018-12-05 17:57:47.955 - error: Caught by controller[0]: at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:84:48)
2018-12-05 17:57:47.955 - error: Caught by controller[0]: at Object. (/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
2018-12-05 17:57:47.956 - error: Caught by controller[0]: at Module._compile (module.js:652:30)
2018-12-05 17:57:47.956 - error: host.raspberrypi instance system.adapter.ham.0 terminated with code 0 (OK)
2018-12-05 17:57:47.956 - info: host.raspberrypi Restart adapter system.adapter.ham.0 because enabled


so das kommt jetzt raus. bin am ende! mit meinem dau wissen komm ich  nicht weiter

**Comment by Apollon77** [comment]
Hast du deine nodejs Version geändert? Führe mal "npm rebuild" in deinem globalen homebridge ordner aus bzw installiere neu. Hat mit dem Adapter an sich nichts zu tun! (sollte zumindestens nicht)

**Comment by Apollon77** [comment]
Node so zu installieren ist in meinen Augen eine schlimme Idee ... sorry. Du hast es manuell installiert also musst Du es manuell wieder wegwerfen. Sorry.
Node besser installieren so: https://github.com/nodesource/distributions#debinstall

**Comment by fighterzg6** [comment]
Hab jetzt alles probiert, bekomme es einfach nicht hin

**Comment by Apollon77** [comment]
Ja? Fehlt da Text?

**Comment by fighterzg6** [comment]
wo?

**Comment by Apollon77** [comment]
Im letzten Post von Dir.

**Comment by Apollon77** [comment]
Aahhh mein Handy client hat bei dem komischen Zeichen oben abgeschnitten.

Was heisst "geht nichts mehr"? Mal bitte mit Debug starten bzew am besten an der Kommandozeile mit

DEBUG=* node /opt/iobroker/node_modules/iobroker-ham/main.js --force --logs

**Comment by Apollon77** [comment]
Any infos?

**Comment by Apollon77** [comment]
Released in 1.0.0

**Comment by Apollon77** [comment]
Fuck ... ne blödsinn weil das DEBUG=* jetzt zuviel macht :-(

lass mal das "DEBUG=* am Anfang weg bitte.

Ansonsten hab ich nur das gefunden:

{ Error: EACCES: permission denied, open '/opt/iobroker/log/iobroker.2018-12-18.log'
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/opt/iobroker/log/iobroker.2018-12-18.log' }

Schau mal das Du den Befehl als der User startest unter dem auch iobroker läuft. Der kann nicht ins Log schreiben bei dem manuellen aufruf scheinbar

**Comment by fighterzg6** [comment]
Und hast du etwas gefunden!?!

**Comment by Apollon77** [comment]
Es ist wieder ein node versions Unterschied. Als ob du global eine andere node Version nutzt als über iobroker. 

Was sagt 

node -v
nodejs -v
npm -v

Das globale homebridge hast du auch frisch kompiliert und gebaut? Ggf geh mal in das angegebene Verzeichnis wo das Problem ist und mach da ein 

npm rebuild

**Comment by Apollon77** [comment]
Ps: sorry die Mail was wohl untergegangen das du was geschrieben hattest.

**Comment by fighterzg6** [comment]
Globaler Homebridge-Pfad /usr/local/lib/node_modules/homebridge/
Globaler Homebridge-Konfigurationsverzeichnispfad /var/homebridge/

er findet alle Geräte, startet auch die plugins, aber die homebridge selber nicht

**Comment by Apollon77** [comment]
Dann bitte Debug Log davon. Insecure steht auf was? Mal getestet ob das eine Auswirkung hat?

**Comment by fighterzg6** [comment]
[iobroker.2019-01-08.log](https://github.com/ioBroker/ioBroker.ham/files/2736579/iobroker.2019-01-08.log)

**Comment by Apollon77** [comment]
Hm ... Das Log zeigt

```
2019-01-08 12:12:54.310  - [31merror[39m: Caught by controller[3]: { Error: EACCES: permission denied, open '/var/homebridge/accessories/cachedAccessories'
2019-01-08 12:12:54.310  - [31merror[39m: Caught by controller[3]:     at Object.fs.openSync (fs.js:660:18)
2019-01-08 12:12:54.311  - [31merror[39m: Caught by controller[3]:     at Object.fs.writeFileSync (fs.js:1319:33)
2019-01-08 12:12:54.311  - [31merror[39m: Caught by controller[3]:     at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
2019-01-08 12:12:54.311  - [31merror[39m: Caught by controller[3]:     at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
2019-01-08 12:12:54.311  - [31merror[39m: Caught by controller[3]:     at Server._updateCachedAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:544:20)
2019-01-08 12:12:54.311  - [31merror[39m: Caught by controller[3]:     at Server._teardown (/usr/local/lib/node_modules/homebridge/lib/server.js:549:8)
2019-01-08 12:12:54.311  - [31merror[39m: Caught by controller[3]:     at Object.end (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:265:16)
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[3]:     at process.on (/opt/iobroker/node_modules/iobroker.ham/main.js:38:51)
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[3]:     at process.emit (events.js:185:15)
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[3]:   errno: -13,
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[3]:   code: 'EACCES',
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[3]:   syscall: 'open',
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[3]:   path: '/var/homebridge/accessories/cachedAccessories' }
2019-01-08 12:12:54.312  - [31merror[39m: Caught by controller[4]: fs.js:660
2019-01-08 12:12:54.313  - [31merror[39m: Caught by controller[4]:   return binding.open(pathModule.toNamespacedPath(path),
```
Ist das schon behoben weil tritt beim zweiten Versuch nicht mehr auf?

Generell ist es aber kein Debug Log :-)
Unter Instanzen -> Expertenmodus -> Spalte Logstufe das Loglevel auf debug setzen.

Dann das Log bitte nochmal :-)

**Comment by fighterzg6** [comment]
[iobroker.2019-01-08.log.html.pdf](https://github.com/ioBroker/ioBroker.ham/files/2736676/iobroker.2019-01-08.log.html.pdf)

**Comment by Apollon77** [comment]
Can you please try is setting insecure mode or not makes any difference?

**Comment by fighterzg6** [comment]
es ändert sich nichts

**Comment by fighterzg6** [comment]
sagt immer noch dienst nicht gestartet

**Comment by Apollon77** [comment]
Und der Haken im Admin bei "Global mode" ist wirkloich gesetzt??

Bzw mach mal folgendes:
Im Admin unter "Objekte" den Expertenmodus an, alle filter weg (vor allem der wo an sich "state "steht. Dann nach system.adapter.ham.0 suchen und bei diesem "Ordner" rechts auf den Stuft Klicken. Dann gibts in dem Fenster was aufgeht ein "Raw (Experts only)" und da ist ein json. das würde ich gern mal sehen :-)

**Comment by fighterzg6** [comment]
[raw.pdf](https://github.com/ioBroker/ioBroker.ham/files/2736876/raw.pdf)

**Comment by fighterzg6** [comment]
bitteschön

**Comment by fighterzg6** [comment]
Grüße, und was gefunden?

**Comment by Apollon77** [comment]
Noch keine Zeit gehabt. Im automatischen test tut alles ... ich kapiere es nicht. Einzige Idee die ich hätte: mach Du mal testweise nur einen deiner Platforms und schau ob es dann tut und finde ggf raus ob es damit was zu tun hat.
