### ISSUE TITLE
Ids are not allowed to end in "."

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.ham#182]
Plugin: homebridge-blink-for-home

```
2021-07-28 13:57:51.143  - [31merror[39m: ham.0 (5531) The id "Blink-Blink-***-usw." is invalid. Ids are not allowed to end in "."
    at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1846:40)
    at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.ham/main.js:79:25)
    at processImmediate (internal/timers.js:458:21)
```

In der Blink-App ist die Bezeichnung eines Syncmoduls mit Punkt erlaubt.

Sollte der Adapter hier vielleicht den Punkt automatisch durch ein anderes Zeichen ersetzen?

**Comment by Apollon77** [comment]
Ja scheint wohl so :-(

**Comment by Apollon77** [comment]
Ein vollständiges und unverändertes Log wäre aber hilfreich

**Comment by RP70DP** [comment]
Dieselben Zeilen nochmal, nur dass die *** durch das eigentliche Wort ersetzt sind? Oder welche Zeilen sind von Interesse?

**Comment by RP70DP** [comment]
Okay, muss ich mal schauen. Ich mache mich hier aber nicht komplett nackig, Bezeichnungen werde ich durch * ersetzen.

Sowas macht der Adapter auch:
`2021-07-28 11:03:39.873  - [33mwarn[39m: ham.0 (4093) State "ham.0.Blink-Blink-***.Privacy-Mode.On" has no existing object, this might lead to an error in future versions`

**Comment by RP70DP** [comment]
Log im Debug-Modus:

```
2021-07-28 19:32:31.651  - [34mdebug[39m: ham.0 (8456) [2021-7-28 19:32:31] [Blink] Init Blink
2021-07-28 19:36:12.981  - [34mdebug[39m: ham.0 (8456) Homebridge Wrapper Bridge publish {"username":"FF:FF:FF:FF:FF:FF","port":0,"pincode":"0","category":2,"addIdentifyingMaterial":true,"advertiser":"bonjour-hap"}
2021-07-28 19:36:13.257  - [34mdebug[39m: ham.0 (8456) Preparing Advertiser for 'Homebridge-Wrapper-Bridge 533C' using bonjour-hap backend!
2021-07-28 19:36:14.212  - [31merror[39m: ham.0 (8456) The id "Blink-Blink-Lichtschaechte-usw." is invalid. Ids are not allowed to end in "."
    at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1846:40)
    at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.ham/main.js:79:25)
    at processImmediate (internal/timers.js:458:21)
```
Wenn das nicht reicht, dann muss ich das Log-File schicken.

Was für ein Link?

**Comment by Apollon77** [comment]
Ja, bitte schicken, ist zuwenig. Was meinst du mit Link? Meine E-Mail steht schon oben

**Comment by RP70DP** [comment]
Erledigt.

**Comment by Apollon77** [comment]
Also workaround bitte vorerst namen ändern das kein Punkt am Ende ist :-)

**Comment by Apollon77** [comment]
Will be adjiusted in next version

**Comment by RP70DP** [comment]
I've already renamed my affected syncmodule in Blink-App, so i will not try out the fix.

Nevertheless thanks for fixing!

**Comment by Apollon77** [comment]
The "fix" will come as next major update which adjusts maybe also other characters ... so ...  but all good for your case
