### ISSUE TITLE
The requested accessory was not registered by any plugin

### ISSUE THREAD

**Issue by vladitep** [ioBroker/ioBroker.ham#2]
ok, i am set "homebridge-xiaomi-air-purifier" at "additional modules NPM", then set correct data at config file:
 {
      "accessory": "XiaoMiAirPurifier",
      "name": "Air Purifier",
      "showTemperature": true,
      "showHumidity": true,
      "showAirQuality": true,
      "address": "my ip",
      "token": "mytoken",
      "model": "zhimi.airpurifier.m1"
    }

At first start driver, "xiaomi-air-purifier" plugin get installed correct, but driver does not start with errors:

```
host.domoticz | 2018-06-19 03:56:53.222 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
-- | -- | -- | --
host.domoticz | 2018-06-19 03:56:53.222 | error | Caught by controller[4]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:244:12)
host.domoticz | 2018-06-19 03:56:53.222 | error | Caught by controller[4]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:319:9)
host.domoticz | 2018-06-19 03:56:53.221 | error | Caught by controller[4]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2432:25)
host.domoticz | 2018-06-19 03:56:53.221 | error | Caught by controller[4]: at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:175:23)
host.domoticz | 2018-06-19 03:56:53.221 | error | Caught by controller[4]: at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:211:57)
host.domoticz | 2018-06-19 03:56:53.221 | error | Caught by controller[4]: at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/wrapper-handler.js:90:23)
host.domoticz | 2018-06-19 03:56:53.220 | error | Caught by controller[4]: at HomebridgeWrapper.init (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/index.js:176:17)
host.domoticz | 2018-06-19 03:56:53.220 | error | Caught by controller[4]: at Server.run (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/server.js:86:38)
host.domoticz | 2018-06-19 03:56:53.220 | error | Caught by controller[4]: at Server._loadAccessories (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/server.js:284:42)
host.domoticz | 2018-06-19 03:56:53.220 | error | Caught by controller[4]: at API.accessory (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/api.js:64:13)
host.domoticz | 2018-06-19 03:56:53.220 | error | Caught by controller[4]: Error: The requested accessory 'XiaoMiAirPurifier' was not registered by any plugin.
host.domoticz | 2018-06-19 03:56:53.219 | error | Caught by controller[3]: [6/19/2018, 3:56:52 AM] No plugins found. See the README for information on installing plugins.
host.domoticz | 2018-06-19 03:56:53.219 | error | Caught by controller[3]: [6/19/2018, 3:56:52 AM] ====================
host.domoticz | 2018-06-19 03:56:53.219 | error | Caught by controller[3]: at require (internal/module.js:20:19)
host.domoticz | 2018-06-19 03:56:53.219 | error | Caught by controller[3]: at Module.require (module.js:497:17)
host.domoticz | 2018-06-19 03:56:53.219 | error | Caught by controller[3]: at Function.Module._load (/opt/iobroker/node_modules/iobroker.ham/node_modules/mock-require/index.js:29:22)
host.domoticz | 2018-06-19 03:56:53.218 | error | Caught by controller[3]: at Function.Module._load (module.js:438:3)
host.domoticz | 2018-06-19 03:56:53.218 | error | Caught by controller[3]: at tryModuleLoad (module.js:446:12)
host.domoticz | 2018-06-19 03:56:53.218 | error | Caught by controller[3]: at Module.load (module.js:487:32)
host.domoticz | 2018-06-19 03:56:53.218 | error | Caught by controller[3]: at Object.Module._extensions..js (module.js:579:10)
host.domoticz | 2018-06-19 03:56:53.218 | error | Caught by controller[3]: at Module._compile (module.js:542:28)
host.domoticz | 2018-06-19 03:56:53.217 | error | Caught by controller[3]: at Object.runInThisContext (vm.js:97:10)
host.domoticz | 2018-06-19 03:56:53.217 | error | Caught by controller[3]: at createScript (vm.js:56:10)
host.domoticz | 2018-06-19 03:56:53.217 | error | Caught by controller[3]: SyntaxError: Unexpected token function
host.domoticz | 2018-06-19 03:56:53.217 | error | Caught by controller[3]: ^^^^^^^^
host.domoticz | 2018-06-19 03:56:53.216 | error | Caught by controller[3]: init: async function() {
host.domoticz | 2018-06-19 03:56:53.216 | error | Caught by controller[3]: [6/19/2018, 3:56:52 AM] /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-xiaomi-air-purifier/index.js:107
host.domoticz | 2018-06-19 03:56:53.216 | error | Caught by controller[3]: [6/19/2018, 3:56:52 AM] ERROR LOADING PLUGIN homebridge-xiaomi-air-purifier:
host.domoticz | 2018-06-19 03:56:53.215 | error | Caught by controller[3]: [6/19/2018, 3:56:52 AM] ====================
host.domoticz | 2018-06-19 03:56:53.215 | error | Caught by controller[2]: [6/19/2018, 3:56:52 AM] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-xiaomi-air-purifier' since we already loaded the same plugin from '/opt/iobroker/no
host.domoticz | 2018-06-19 03:56:53.215 | error | Caught by controller[1]: [6/19/2018, 3:56:52 AM] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
host.domoticz | 2018-06-19 03:56:53.215 | error | Caught by controller[1]: [6/19/2018, 3:56:52 AM] Plugin /opt/iobroker/node_modules/homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'.
host.domoticz | 2018-06-19 03:56:53.213 | error | Caught by controller[0]: [6/19/2018, 3:56:51 AM] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ham.0 | 2018-06-19 03:56:53.099 | error | uncaught exception: The requested accessory 'XiaoMiAirPurifier' was not registered by any plugin.

```
Same with other xiaomi humidifier plugin. What i can do with that?

**Comment by vladitep** [comment]
By the way, at previous version of *.ham all plugins worked correct with wrapper and with global homebridge mode

**Comment by vladitep** [comment]
ok, i got it. Ham started without errors, but only when i manually install homebridge plugins with -g key.

**Comment by Apollon77** [comment]
You should not install them global. 

The error more looks to me that the plugin needs a higher nodejs version then you have installed. 
What node Version you use?

Does your last comment mean that it works now? No, or?!

BTW: Synology homebridge was also reported in forum as not working. But this is the plugin and not ham ;-)

**Comment by Apollon77** [comment]
BTW: the syntax error „async function“ means that the plugin needs at lest nodejs 8!!

If you have 6 still then this is your root cause. 

Please uninstall the global installed plugin because will not be used but the local instead as you can see in the log messages.

**Comment by vladitep** [comment]
oh, yes i use node 6.11.  I'll try to update, thank you
