### ISSUE TITLE
Feature request: Update plugins

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.ham#29]
It would be great to have a possibility to update the plugins directly from the adapter.
Currently that needs to be done via the command line.

**Comment by Apollon77** [comment]
Hm ... normally on each start a "npm install" should be executed which updates it automatically ... I will check it

**Comment by Apollon77** [comment]
The upcoming 1.1.0 will bring an option in admin to update/reinstall all plugins on next start of adapter instance.

I have a very experimental new verison on Github. I still work on testing for windows and there may be problems, especially in global mode.
And it still needs detailed testing, but updating should already work

**Comment by cburghardt** [comment]
2019-07-02 23:54:23.773  - error: ham.0 uncaught exception: Cannot read property 'registerExistingAccessory' of undefined
2019-07-02 23:54:23.802  - error: Caught by controller[0]: TypeError: Cannot read property 'registerExistingAccessory' of undefined
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:173:39)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Socket.that.objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2693:25)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-07-02 23:54:23.803  - error: Caught by controller[0]:     at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
2019-07-02 23:54:23.806  - error: Caught by controller[0]:     at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)

**Comment by Apollon77** [comment]
Can you please enable debug logging and post the full log of an adapter start please?
And also provide Info on your settings.

**Comment by Apollon77** [comment]
Log not needed. I know the reason. Will be fixed soon

**Comment by cburghardt** [comment]
Alright but just for completeness I am running with wrapper mode

**Comment by Apollon77** [comment]
Please retry, error should be fixed

**Comment by cburghardt** [comment]
Yes, I can confirm the error is gone

**Comment by Apollon77** [comment]
Cool, then try to go to admin, check the "update npm modules" checkbox and save. Then adapter should restart, reinstall all plugins, then restart itself again, this time without reinstalling stuff. After that the "update checkbox" should be cleared again

**Comment by Apollon77** [comment]
fixed by 1.1.1
