### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by iGodPhil** [ioBroker/ioBroker.ham#322]
Ich versuche grade vergebens den HAM Adapter zum Laufen zu bekommen. Homebridge läuft als global und der Adapter dementsprechend auch als global eingestellt. Allerdings erscheint im Log permanent die Meldung, dass die Adresse mit angegebenen Port in use ist woraufhin der Adapter abstürzt. Naja auf dem Port läuft halt die Homebridge einwandfrei...
Da es sich um eine frische Installation von Homebridge nach offizieller Anleitung handelt, sind alle Homebridge Plugins auf aktuellem Stand. Im ioBroker ist ebenfalls alles up to date. `node -v -> v14.19.0`

Der User iobroker wurde zur Gruppe homebridge hinzugefügt und die Rechte des Ordner persist mit chmod -R 777 angepasst. 

```
2022-03-03 21:38:56.873 - debug: ham.0 (116946) [3/3/2022, 9:38:56 PM] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x0017880106ee2708/get': '{"state":0,"brightness":0,"color_temp":0,"color":0}'
--
2022-03-03 21:38:57.004 - error: ham.0 (116946) uncaught exception: listen EADDRINUSE: address already in use :::51990
2022-03-03 21:38:57.012 - error: ham.0 (116946) Error: listen EADDRINUSE: address already in use :::51990
at Server.setupListenHandle [as _listen2] (net.js:1331:16)
at listenInCluster (net.js:1379:12)
at Server.listen (net.js:1465:7)
at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
at MyBridge. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:18)
at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
at new Promise ()
2022-03-03 21:38:57.012 - error: ham.0 (116946) Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use :::51990
2022-03-03 21:38:57.013 - warn: ham.0 (116946) Exception: Error: listen EADDRINUSE: address already in use :::51990
2022-03-03 21:38:57.025 - info: ham.0 (116946) cleaned everything up...
2022-03-03 21:38:57.033 - info: ham.0 (116946) terminating
2022-03-03 21:38:57.034 - warn: ham.0 (116946) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-03 21:38:57.364 - debug: ham.0 (116946) [3/3/2022, 9:38:57 PM] [zigbee2mqtt] Connected to MQTT server
--
2022-03-03 21:38:57.482 - debug: ham.0 (116946) [3/3/2022, 9:38:57 PM] [zigbee2mqtt] Using Zigbee2MQTT v1.22.2 (identified via zigbee2mqtt/bridge/info)
2022-03-03 21:38:57.528 - info: mqtt.0 (80004) State value to set for "mqtt.0.zigbee2mqtt.Flurlampe_2.linkquality" has to be type "string" but received type "number"
2022-03-03 21:38:57.541 - info: mqtt.0 (80004) State value to set for "mqtt.0.zigbee2mqtt.Stehlampe.linkquality" has to be type "string" but received type "number"
2022-03-03 21:38:57.582 - info: mqtt.0 (80004) State value to set for "mqtt.0.zigbee2mqtt.Flurlampe_1.linkquality" has to be type "string" but received type "number"
2022-03-03 21:38:58.159 - info: mqtt.0 (80004) State value to set for "mqtt.0.zigbee2mqtt.Stehlampe.linkquality" has to be type "string" but received type "number"
2022-03-03 21:38:59.155 - info: mqtt.0 (80004) State value to set for "mqtt.0.zigbee2mqtt.Stehlampe.linkquality" has to be type "string" but received type "number"
2022-03-03 21:38:59.256 - info: ham.0 (116946) terminating with timeout
2022-03-03 21:38:59.692 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.695 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.695 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.695 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.695 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.696 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.697 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.697 - warn: ham.0 (116946) get state error: DB closed
2022-03-03 21:38:59.709 - warn: ham.0 (116946) Error while getting current value: -70405
2022-03-03 21:39:00.030 - warn: ham.0 (116946) Error while getting current value: -70405
2022-03-03 21:39:00.601 - warn: ham.0 (116946) Error while getting current value: -70405
2022-03-03 21:39:01.057 - warn: ham.0 (116946) Error while getting current value: -70405
2022-03-03 21:39:01.372 - warn: ham.0 (116946) Error while getting current value: -70405
2022-03-03 21:39:01.611 - warn: ham.0 (116946) get state error: Connection is closed.
2022-03-03 21:39:01.611 - warn: ham.0 (116946) get state error: Connection is closed.
```

**Comment by iGodPhil** [comment]
netstat gibt mir ebenfalls nur den homebridge Dienst aus:

```
root@iobroker:~# netstat -anp --tcp --udp | grep "51990"
tcp6       0      0 :::51990                :::*                    LISTEN      133797/homebridge   
tcp6       0      0 10.0.30.2:51990         10.0.10.8:55349         ESTABLISHED 133797/homebridge   
tcp6       0    232 10.0.30.2:51990         10.0.10.7:50499         ESTABLISHED 133797/homebridge   
tcp6       0      0 10.0.30.2:51990         10.0.20.15:52712        ESTABLISHED 133797/homebridge   
tcp6       0      0 10.0.30.2:51990         10.0.10.3:59802         ESTABLISHED 133797/homebridge   
tcp6       0      0 10.0.30.2:51990         10.0.10.10:50699        ESTABLISHED 133797/homebridge   
tcp6       0      0 10.0.30.2:51990         10.0.10.14:61829        ESTABLISHED 133797/homebridge   
tcp6       0      0 10.0.30.2:51990         10.0.10.4:59912         ESTABLISHED 133797/homebridge 
```

**Comment by Apollon77** [comment]
Ich glaube Du hast einen Denkfehler: "Ham adapter mit Homebridge im globalen Modus" bedeutet das ein global installiertes homebridge vom Adapter gestartet wird und er sich einklinkt. Du darfst das nicht ausserhalb vom Adapter starten

**Comment by iGodPhil** [comment]
Ah ok, das hab ich dann in der Tat falsch verstanden. Vielen Dank, jetzt läuft alles einwandfrei.

Könntest du mir noch verraten, wie ich das log auch im config-ui-x angezeigt bekomme? Also wo wird das file abgelegt oder mit welchem command kann ich es abrufen. Aktuell kann ich es nur in der iobroker Oberfläche sehen.
