### ISSUE TITLE
homebridge-webos-tv Plugins don't work

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.ham#33]
log:
```
ham.0 cleaned everything up...
ham.0 Exception: ReferenceError: findDevices is not defined
Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ReferenceError: findDevices is not defined
    at new webosTvAccessory (/usr/lib/node_modules/homebridge-webos-tv-ext/index.js:37:2)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:260:12)
    at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:232:35)
    at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:175:27)
    at Socket.that.objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2693:25)
    at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
    at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
    at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:322:16)
    at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:451:14)
    at WS.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:268:10)
    at WS.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:145:8)
host.iobroker2-1 instance system.adapter.ham.0 terminated with code 0 (OK)
```

config.json
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:38",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "cmdSwitch2",
            "name": "CMD Switch",
            "switches": [
                {
                    "name": "Playstation 4",
                    "on_cmd": "ps4-waker",
                    "off_cmd": "ps4-waker standby",
                    "state_cmd": "ps4-waker search | grep -i '200 Ok'",
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000,
                    "manufacturer": "Sony Corporation",
                    "model": "CUH-1001A",
                    "serial": "XXXXXXXXXXX"
                }
            ]
        },
        {
            "name": "Config",
            "port": 8888,
            "auth": "none",
            "theme": "red",
            "tempUnits": "c",
            "log": {
                "method": "systemd",
                "path": "/opt/log/homebridge.log"
            },
            "platform": "config"
        },
        {
            "veraIP": "192.168.1.54",
            "includesensor": true,
            "platform": "Vera",
            "dimmertest": true,
            "ignorescenes": [],
            "ignoredevices": [
                8
            ],
            "name": "Vera"
        }
    ],
    "accessories": [
        {
            "accessory": "GreeHeaterCooler",
            "host": "192.168.1.34",
            "name": "Living room AC",
            "acModel": "Gree V2",
            "acTempSensorShift": 40,
            "updateInterval": 10000
        },
        {
            "name": "My LG TV",
            "mac": "78:5D:C8:C1:80:4E",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "true",
            "volumeLimit": 100,
            "channelControl": true,
            "mediaControl": false,
            "remoteSequenceButtons": [
                {
                    "sequence": [],
                    "interval": 500
                }
            ],
            "accessory": "webostv"
        }
    ]
}

```

**Comment by Apollon77** [comment]
And it was wortking before/is working in a plain homebridge installation?

**Comment by Apollon77** [comment]
Plugin is broken ...


// --== MAIN SETUP ==--
function webosTvAccessory(log, config, api) {
        findDevices()
    this.log = log;
    this.port = 3000;

... but this method "findeDevices" is not existing, so it will also not work  ... There is a method called "findDevice" that finds one with a specific mac ... contact the plugin developer
