### ISSUE TITLE
Starten im "Lokaler Modus" geht nicht

### ISSUE THREAD

**Issue by Kleinstein-github** [ioBroker/ioBroker.ham#38]
host.raspberrypi | 2019-08-17 17:11:16.072 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2019-08-17 17:11:16.072 | error | Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
host.raspberrypi | 2019-08-17 17:11:16.072 | error | Caught by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.raspberrypi | 2019-08-17 17:11:16.072 | error | Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
host.raspberrypi | 2019-08-17 17:11:16.072 | error | Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
host.raspberrypi | 2019-08-17 17:11:16.072 | error | Caught by controller[0]: at Socket.that.objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2696:25)
host.raspberrypi | 2019-08-17 17:11:16.071 | error | Caught by controller[0]: at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:177:27)
host.raspberrypi | 2019-08-17 17:11:16.071 | error | Caught by controller[0]: at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:276:39)
host.raspberrypi | 2019-08-17 17:11:16.071 | error | Caught by controller[0]: at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:279:14)
host.raspberrypi | 2019-08-17 17:11:16.071 | error | Caught by controller[0]: at new Server (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge/lib/server.js:56:38)
host.raspberrypi | 2019-08-17 17:11:16.071 | error | Caught by controller[0]: at Server._loadConfig (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge/lib/server.js:230:32)
host.raspberrypi | 2019-08-17 17:11:16.069 | error | Caught by controller[0]: TypeError: Cannot read property 'username' of undefined
host.raspberrypi | 2019-08-17 17:11:12.628 | info | instance system.adapter.ham.0 started with pid 32200
host.raspberrypi | 2019-08-17 16:10:42.588 | info | Restart adapter system.adapter.ham.0 because enabled

**Comment by Kleinstein-github** [comment]
node v10.16.1
npm v6.10.2
