### ISSUE TITLE
Globaler Modus startet nicht EADDRINUSE

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.ham#454]
Hab versucht den globalen Modus zu installieren und zu starten.

leider gibt das log dann immer folgenden Fehler aus:

`<html>
<body>

ham.0 | 2022-12-04 00:40:11.851 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use :::51178
-- | -- | -- | --
ham.0 | 2022-12-04 00:40:11.849 | error | Error: listen EADDRINUSE: address already in use :::51178 at Server.setupListenHandle [as _listen2] (node:net:1463:16) at listenInCluster (node:net:1511:12) at Server.listen (node:net:1599:7) at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20) at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21) at MyBridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18) at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27) at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57) at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75 at new Promise (<anonymous>)
ham.0 | 2022-12-04 00:40:11.841 | error | uncaught exception: listen EADDRINUSE: address already in use :::51178

</body>
</html>`

**Comment by unstressable** [comment]
Ätzend, ich habe den 3. Schritt: "uninstall hb-service (sudo hb-service uninstall)" ausgelassen, da ich dachte, dass dieser nur für die Deinstallation nötigt ist und ich ja installieren wollte.

Nachdem ich diesen Schritt nachgeholt habe scheint die Installation nun zu laufen...

**Comment by unstressable** [comment]
Nach der Installation hat Homebridge beim Installieren der Module auch gemeckert, dass der User ioBroker keine Rechte für den Ordner: /usr/lib/node_modules/ hat.

Folgender Befehl shuf Abhilfe:
sudo chown -R iobroker /usr/lib/node_modules/
