### ISSUE TITLE
Immer wieder error | Exception-Code: EADDRINUSE

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.ham#455]
```
<html>
<body>
<!--StartFragment-->

ham.0 | 2022-12-04 13:58:08.895 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use :::51442
-- | -- | -- | --
ham.0 | 2022-12-04 13:58:08.894 | error | Error: listen EADDRINUSE: address already in use :::51442 at Server.setupListenHandle [as _listen2] (node:net:1463:16) at listenInCluster (node:net:1511:12) at Server.listen (node:net:1599:7) at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20) at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21) at MyBridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18) at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27) at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57) at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:115:62) at processTicksAndRejections (node:internal/process/task_queues:96:5)
ham.0 | 2022-12-04 13:58:08.888 | error | uncaught exception: listen EADDRINUSE: address already in use :::51442

<!--EndFragment-->
</body>
</html>
```

**Comment by Apollon77** [comment]
Dieser Fehler bedeutet das homebridge mit den gleichen Settings auf dem gleichen Host nochmals läuft. Bitte vollständiges ioBroker log von solchen situationen (und nicht zu knapp davor oder danach oder host Logs und ham logs.

**Comment by unstressable** [comment]
Hier etwas mehr:

`<html>
<body>


at Server.setupListenHandle [as _listen2] (node:net:1463:16)
--
at listenInCluster (node:net:1511:12)
at Server.listen (node:net:1599:7)
at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
at MyBridge. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-04 15:09:04.871 - error: ham.0 (16687) Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use :::51442
2022-12-04 15:09:04.873 - warn: ham.0 (16687) Exception: Error: listen EADDRINUSE: address already in use :::51442
2022-12-04 15:09:05.391 - warn: ham.0 (16687) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-12-04 15:09:06.353 - error: host.ioBroker-RasPi4 Caught by controller[0]: [4.12.2022, 15:09:00] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
2022-12-04 15:09:06.354 - error: host.ioBroker-RasPi4 Caught by controller[1]: [4.12.2022, 15:09:00] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
2022-12-04 15:09:06.355 - error: host.ioBroker-RasPi4 Caught by controller[2]: [4.12.2022, 15:09:00] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-eufy-security' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-eufy-security'.
2022-12-04 15:09:06.356 - error: host.ioBroker-RasPi4 Caught by controller[3]: [4.12.2022, 15:09:00] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-mi-humidifier' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-mi-humidifier'.
2022-12-04 15:09:06.356 - error: host.ioBroker-RasPi4 Caught by controller[4]: [4.12.2022, 15:09:00] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-yeelighter' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-yeelighter'.
2022-12-04 15:09:06.357 - error: host.ioBroker-RasPi4 Caught by controller[5]: [4.12.2022, 15:09:00] Plugin /usr/lib/node_modules/homebridge does not have a package name that begins with 'homebridge-' or '@scope/homebridge-.
2022-12-04 15:09:06.357 - error: host.ioBroker-RasPi4 Caught by controller[6]: [4.12.2022, 15:09:03] [Yeelighter] ingoring device with corrupt DeviceInfo {
2022-12-04 15:09:06.358 - error: host.ioBroker-RasPi4 Caught by controller[6]: location: 'yeelight://undefined',
2022-12-04 15:09:06.358 - error: host.ioBroker-RasPi4 Caught by controller[6]: id: undefined,
2022-12-04 15:09:06.359 - error: host.ioBroker-RasPi4 Caught by controller[6]: model: undefined,
2022-12-04 15:09:06.359 - error: host.ioBroker-RasPi4 Caught by controller[6]: support: undefined,
2022-12-04 15:09:06.360 - error: host.ioBroker-RasPi4 Caught by controller[6]: power: false,
2022-12-04 15:09:06.360 - error: host.ioBroker-RasPi4 Caught by controller[6]: bright: 0,
2022-12-04 15:09:06.361 - error: host.ioBroker-RasPi4 Caught by controller[6]: color_mode: -1,
2022-12-04 15:09:06.361 - error: host.ioBroker-RasPi4 Caught by controller[6]: ct: 0,
2022-12-04 15:09:06.362 - error: host.ioBroker-RasPi4 Caught by controller[6]: rgb: 'string',
2022-12-04 15:09:06.362 - error: host.ioBroker-RasPi4 Caught by controller[6]: hue: 0,
2022-12-04 15:09:06.363 - error: host.ioBroker-RasPi4 Caught by controller[6]: sat: 0,
2022-12-04 15:09:06.363 - error: host.ioBroker-RasPi4 Caught by controller[6]: host: 'string',
2022-12-04 15:09:06.364 - error: host.ioBroker-RasPi4 Caught by controller[6]: port: 0,
2022-12-04 15:09:06.364 - error: host.ioBroker-RasPi4 Caught by controller[6]: debug: false,
2022-12-04 15:09:06.367 - error: host.ioBroker-RasPi4 Caught by controller[6]: trackedAttributes: [],
2022-12-04 15:09:06.368 - error: host.ioBroker-RasPi4 Caught by controller[6]: fw_ver: '0,0.0',
2022-12-04 15:09:06.368 - error: host.ioBroker-RasPi4 Caught by controller[6]: name: 'string'
2022-12-04 15:09:06.369 - error: host.ioBroker-RasPi4 Caught by controller[6]: }
2022-12-04 15:09:06.369 - error: host.ioBroker-RasPi4 instance system.adapter.ham.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-12-04 15:09:06.370 - info: host.ioBroker-RasPi4 Restart adapter system.adapter.ham.0 because enabled
2022-12-04 15:09:36.770 - info: host.ioBroker-RasPi4 instance system.adapter.ham.0 started with pid 17129
2022-12-04 15:09:50.332 - error: ham.0 (17129) uncaught exception: listen EADDRINUSE: address already in use :::51442
2022-12-04 15:09:50.338 - error: ham.0 (17129) Error: listen EADDRINUSE: address already in use :::51442
at Server.setupListenHandle [as _listen2] (node:net:1463:16)
at listenInCluster (node:net:1511:12)
at Server.listen (node:net:1599:7)
at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
at MyBridge. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-04 15:09:50.340 - error: ham.0 (17129) Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use :::51442
2022-12-04 15:09:50.345 - warn: ham.0 (17129) Exception: Error: listen EADDRINUSE: address already in use :::51442
2022-12-04 15:09:50.921 - warn: ham.0 (17129) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-12-04 15:09:51.828 - error: host.ioBroker-RasPi4 Caught by controller[0]: [4.12.2022, 15:09:45] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
2022-12-04 15:09:51.829 - error: host.ioBroker-RasPi4 Caught by controller[1]: [4.12.2022, 15:09:46] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
2022-12-04 15:09:51.829 - error: host.ioBroker-RasPi4 Caught by controller[2]: [4.12.2022, 15:09:46] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-eufy-security' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-eufy-security'.
2022-12-04 15:09:51.830 - error: host.ioBroker-RasPi4 Caught by controller[3]: [4.12.2022, 15:09:46] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-mi-humidifier' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-mi-humidifier'.
2022-12-04 15:09:51.830 - error: host.ioBroker-RasPi4 Caught by controller[4]: [4.12.2022, 15:09:46] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-yeelighter' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-yeelighter'.
2022-12-04 15:09:51.831 - error: host.ioBroker-RasPi4 Caught by controller[5]: [4.12.2022, 15:09:46] Plugin /usr/lib/node_modules/homebridge does not have a package name that begins with 'homebridge-' or '@scope/homebridge-.
2022-12-04 15:09:51.831 - error: host.ioBroker-RasPi4 Caught by controller[6]: [4.12.2022, 15:09:49] [Yeelighter] ingoring device with corrupt DeviceInfo {
2022-12-04 15:09:51.832 - error: host.ioBroker-RasPi4 Caught by controller[6]: location: 'yeelight://undefined',
2022-12-04 15:09:51.832 - error: host.ioBroker-RasPi4 Caught by controller[6]: id: undefined,
2022-12-04 15:09:51.832 - error: host.ioBroker-RasPi4 Caught by controller[6]: model: undefined,
2022-12-04 15:09:51.833 - error: host.ioBroker-RasPi4 Caught by controller[6]: support: undefined,
2022-12-04 15:09:51.833 - error: host.ioBroker-RasPi4 Caught by controller[6]: power: false,
2022-12-04 15:09:51.834 - error: host.ioBroker-RasPi4 Caught by controller[6]: bright: 0,
2022-12-04 15:09:51.834 - error: host.ioBroker-RasPi4 Caught by controller[6]: color_mode: -1,
2022-12-04 15:09:51.834 - error: host.ioBroker-RasPi4 Caught by controller[6]: ct: 0,
2022-12-04 15:09:51.835 - error: host.ioBroker-RasPi4 Caught by controller[6]: rgb: 'string',
2022-12-04 15:09:51.835 - error: host.ioBroker-RasPi4 Caught by controller[6]: hue: 0,
2022-12-04 15:09:51.836 - error: host.ioBroker-RasPi4 Caught by controller[6]: sat: 0,
2022-12-04 15:09:51.836 - error: host.ioBroker-RasPi4 Caught by controller[6]: host: 'string',
2022-12-04 15:09:51.836 - error: host.ioBroker-RasPi4 Caught by controller[6]: port: 0,
2022-12-04 15:09:51.837 - error: host.ioBroker-RasPi4 Caught by controller[6]: debug: false,
2022-12-04 15:09:51.837 - error: host.ioBroker-RasPi4 Caught by controller[6]: trackedAttributes: [],
2022-12-04 15:09:51.837 - error: host.ioBroker-RasPi4 Caught by controller[6]: fw_ver: '0,0.0',
2022-12-04 15:09:51.838 - error: host.ioBroker-RasPi4 Caught by controller[6]: name: 'string'
2022-12-04 15:09:51.838 - error: host.ioBroker-RasPi4 Caught by controller[6]: }
2022-12-04 15:09:51.839 - error: host.ioBroker-RasPi4 instance system.adapter.ham.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-12-04 15:09:51.840 - info: host.ioBroker-RasPi4 Restart adapter system.adapter.ham.0 because enabled
2022-12-04 15:09:51.840 - warn: host.ioBroker-RasPi4 Do not restart adapter system.adapter.ham.0 because restart loop detected


<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by Apollon77** [comment]
najaa der interessante Part - nämlich was VOR dem ersten Fehler passiert fehlt leider. Weil die Annahme wäre das der Prozess davor nicht beendet wurde - frage ist warum.

PS: Warum nutzt du nicht den Yeelight adapter?

**Comment by unstressable** [comment]
Der Yeelight Adapter ist meiner Meinung nach Schrott, der stürzt die ganze Zeit ab und ist total langsam.
Da arbeitet der "Yeelighter" vom Homebridge deutlich zuverlässiger.
