### ISSUE TITLE
ham started nicht - "Reading destroy"

### ISSUE THREAD

**Issue by adieball** [ioBroker/ioBroker.ham#458]
Ich bekomme den Adapter nicht zum laufen.
Lokal Mode

Error:
`

2022-12-17 18:11:45.631 | warn | Exception: TypeError: Cannot read properties of undefined (reading 'destroy')
-- | -- | --
ham.0 | 2022-12-17 18:11:45.629 | error | Cannot read properties of undefined (reading 'destroy')
ham.0 | 2022-12-17 18:11:45.628 | error | TypeError: Cannot read properties of undefined (reading 'destroy') at /opt/iobroker/node_modules/iobroker.ham/node_modules/hap-nodejs/src/lib/Advertiser.ts:256:29 at Registry._onTearDownComplete (/opt/iobroker/node_modules/iobroker.ham/node_modules/bonjour-hap/lib/Registry.js:67:18) at onbind (/opt/iobroker/node_modules/iobroker.ham/node_modules/multicast-dns/index.js:85:29) at apply (/opt/iobroker/node_modules/iobroker.ham/node_modules/thunky/index.js:44:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
ham.0 | 2022-12-17 18:11:45.628 | error | uncaught exception: Cannot read properties of undefined (reading 'destroy')

`

bin für jeden Tip dankbar.

IObroker läuft in einem Docker Container.
Node.js = 16.16

Danke!

**Comment by Apollon77** [comment]
Welche Version wird denn genutzt?

Bitte poste ein vollständiges Debug log. Der Fehler kommt wohl wenn der Advertiser von HAP-Nodejs beendet werden soll ... komisch. Geht m docker container überhaupt MDNS und sowas?

**Comment by adieball** [comment]
Habe die adapter jetzt mal auf den PI geschoben, habe dort aber das identische Problem.
Was genau möchtest du denn haben in Bezug auf "vollständiges Debug Log"? Wo bekomme ich das her (sorry wenn es blöd nachgefragt ist)

**Comment by Apollon77** [comment]
Am besten ein Silly log: Admin - Instanzen - Expertenmodus aktivieren - ham .0 aufklappen - Loglevel auf "Alles/Silly" setzen

Dann log aus dem Logfile unter /opt/iobroker/log/.... holen und hier als textfile attachen

**Comment by adieball** [comment]
Habe es jetzt mal ohne zusätzlich NPM Adapter installiert, nun geht es.
Werde nun mal mit conifg-ui-x anfangen und schauen wie es geht

**Comment by Apollon77** [comment]
conifg-ui-x geht aber ggf nicht ... siehe Readme

**Comment by adieball** [comment]
welche Readme? In der von HAM adapter finde ich nichts dazu

**Comment by adieball** [comment]
Hmm, rademacher homepilo ist installiert und in der Config drin, aber Objekte werden nicht angelegt ....
Dachte HAM könnte ine Alternative für meinen unstabilen Yahka sein, aber irgendwie komme ich nicht weiter.
Gibt es jemanden der (auch gerne bazahlt) eine Remote Session mit mir macht?

**Comment by Apollon77** [comment]
Mach doch erstmal bitte DAS HIER --> https://github.com/ioBroker/ioBroker.ham/issues/458#issuecomment-1366609124
