### ISSUE TITLE
Envoy-Enphase Plugin is crashing at startup

### ISSUE THREAD

**Issue by ahnungsbefreit** [ioBroker/ioBroker.ham#487]
**Describe the bug**  
HAM Adapter is working for me in Wrapper Mode but for the [Enphase Envoy Pluging](https://github.com/grzegorz914/homebridge-enphase-envoy#readmel) it does not and results in an adapter crash and re-start loops. 

**To Reproduce**  
1. Install the Enphase Plugin "homebridge-enphase-envoy" in HAM
2. Provide some basic dummy configuration like
```
{
    "devices": [
        {
            "envoyFirmware7xx": true,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableDebugMode": true,
            "powerProductionMaxAutoReset": 0,
            "powerProductionMaxDetected": 0,
            "energyProductionLifetimeOffset": 0,
            "powerConsumptionTotalMaxAutoReset": 0,
            "powerConsumptionTotalMaxDetected": 0,
            "energyConsumptionTotalLifetimeOffset": 0,
            "powerConsumptionNetMaxAutoReset": 0,
            "powerConsumptionNetMaxDetected": 0,
            "energyConsumptionNetLifetimeOffset": 0,
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false,
            "name": "Envoy-S",
            "envoyPasswd": "<somePassword>",
            "envoyFirmware7xxToken": "<someToken>",
        }
    ],
    "platform": "enphaseEnvoy"
}
```
3. Update to the latest version of the Plugin 6.30 (but the behavior was the same with previous versions)
4. Watch the log. You will find something like:
```
host.ioBVM-prod2
2023-01-12 12:09:27.280	info	Restart adapter system.adapter.ham.0 because enabled
host.ioBVM-prod2
2023-01-12 12:09:27.278	error	instance system.adapter.ham.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBVM-prod2
2023-01-12 12:09:27.278	error	Caught by controller[2]: [12.1.2023, 12:09:26] [enphaseEnvoy] Device: 192.168.1.132 Envoy-S, requesting envoyBackboneAppData error: Error: connect ENETUNREACH 192.168.1.132:80, reconnect in 15s.
host.ioBVM-prod2
2023-01-12 12:09:27.278	error	Caught by controller[1]: [12.1.2023, 12:09:25] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
host.ioBVM-prod2
2023-01-12 12:09:27.278	error	Caught by controller[0]: [12.1.2023, 12:09:25] Plugin /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ham.0
2023-01-12 12:09:26.713	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
ham.0
2023-01-12 12:09:26.713	info	terminating
ham.0
2023-01-12 12:09:26.707	info	cleaned everything up...
ham.0
2023-01-12 12:09:26.706	info	updateDev Blink-Blink-Haus: name = Blink Blink Haus /type= 11
ham.0
2023-01-12 12:09:26.702	error	Exception-Code: ENETUNREACH: connect ENETUNREACH 192.168.1.132:80
ham.0
2023-01-12 12:09:26.702	error	Error: connect ENETUNREACH 192.168.1.132:80 at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/AxiosError.js:89:14) at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:533:25) at RedirectableRequest.emit (node:events:513:28) at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/iobroker.ham/node_modules/follow-redirects/index.js:14:24) at ClientRequest.emit (node:events:513:28) at Socket.socketErrorListener (node:_http_client:494:9) at Socket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)
ham.0
2023-01-12 12:09:26.671	error	unhandled promise rejection: connect ENETUNREACH 192.168.1.132:80
ham.0
2023-01-12 12:09:26.671	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ham.0
2023-01-12 12:09:24.902	info	Adapter uses Wrapper mode
ham.0
2023-01-12 12:09:24.901	info	All Libraries installed/updated
ham.0
2023-01-12 12:09:24.901	info	Install/Update homebridge-enphase-envoy@6.3.0
ham.0
2023-01-12 12:09:24.901	info	Install/Update homebridge-blink-for-home@3.9.2
ham.0
2023-01-12 12:09:24.900	info	Install/Update the following Libraries: homebridge-blink-for-home@3.9.2, homebridge-enphase-envoy@6.3.0
ham.0
2023-01-12 12:09:24.890	info	starting. Version 5.3.1 in /opt/iobroker/node_modules/iobroker.ham, node: v16.19.0, js-controller: 4.0.24
host.ioBVM-prod2
2023-01-12 12:09:24.272	info	instance system.adapter.ham.0 started with pid 3931562
```

Note: As you can see in the logs, I use also the "Blink for home" plugin but this one works more or less.
**Expected behavior**  
Plugin should work :-)

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 1.30
 - JS-Controller version: 4.0.24 
 - Node version: v16.19.0
 - Operating system:  Debian Bullseye on Proxmox

**Additional context**  
Just in case you are interested: The plugin is used to fetch data from the Enphase solar ("Photovoltaik") system.

**Comment by Apollon77** [comment]
In fact there is an unhandled promise rejection caused by an web call to 192.168.1.132:80 but this host is unreachable ... so this is more an issue in the plugin because it should catch these kind of errors. WHich version of the plugin you used?
There were recently commits in the plugin reposiroty  that contains optimizations in errorhandling (could it be you already use THIS version instead of a official github one?)

**Comment by ahnungsbefreit** [comment]
And you are right: The host IP is wrong. I checked it 1 million times but obviously I was blind. Thanks for the quick reaction, much appreciated!

However, after entering the right IP (and generating a new token, just to be sure) there are no errors in the log any longer but even with "debug" on in the plugin I see no information in the log except
`ham.0
2023-01-12 15:27:48.198	info	Adapter uses Wrapper mode
ham.0
2023-01-12 15:27:48.198	info	All Libraries installed/updated
ham.0
2023-01-12 15:27:48.197	info	Install/Update homebridge-enphase-envoy@6.3.0
ham.0
2023-01-12 15:27:48.197	info	Install/Update homebridge-blink-for-home@3.9.2
ham.0
2023-01-12 15:27:48.196	info	Install/Update the following Libraries: homebridge-blink-for-home@3.9.2, homebridge-enphase-envoy@6.3.0
ham.0
2023-01-12 15:27:48.180	info	starting. Version 5.3.1 in /opt/iobroker/node_modules/iobroker.ham, node: v16.19.0, js-controller: 4.0.24
host.ioBVM-prod2
2023-01-12 15:27:47.654	info	instance system.adapter.ham.0 started with pid 20520`

followed by a lot of info messages for the other plugin.

**Comment by Apollon77** [comment]
Then again we should be on the plugin side ..... I also miss the log line that he even tries to connect to the device

**Comment by ahnungsbefreit** [comment]
That's also my problem: There is no such log line or any other indication on what went wrong.
