### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.ham#57]
I can't start the adapter (global mode). When start with the **homebridge - I** in the console, homebridge starts. When the adapter starts, it returns an error:
```
2020-04-29 08:26:32.554  - [32minfo[39m: ham.0 (25907) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.ham, node: v12.16.2, js-controller: 3.0.20
2020-04-29 08:26:32.574  - [32minfo[39m: ham.0 (25907) No additional Libraries to install ...
2020-04-29 08:26:32.575  - [34mdebug[39m: ham.0 (25907) Use Global Homebridge Path: /usr/lib/node_modules/homebridge/
2020-04-29 08:26:32.840  - [31merror[39m: ham.0 (25907) uncaught exception: Cannot find module '/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once'
Require stack:
- /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js
- /opt/iobroker/node_modules/iobroker.ham/main.js
2020-04-29 08:26:32.841  - [31merror[39m: ham.0 (25907) Error: Cannot find module '/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once'
Require stack:
- /opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js
- /opt/iobroker/node_modules/iobroker.ham/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.Module._load (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/node_modules/mock-require/index.js:30:22)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.init (/opt/iobroker/node_modules/iobroker.ham/lib/global-handler.js:88:12)
    at /opt/iobroker/node_modules/iobroker.ham/main.js:217:39
    at installAllLibraries (/opt/iobroker/node_modules/iobroker.ham/main.js:378:21)
    at /opt/iobroker/node_modules/iobroker.ham/main.js:203:13
    at checkLocalMode (/opt/iobroker/node_modules/iobroker.ham/main.js:397:25)
2020-04-29 08:26:32.841  - [32minfo[39m: ham.0 (25907) cleaned everything up...
2020-04-29 08:26:32.851  - [32minfo[39m: ham.0 (25907) terminating
2020-04-29 08:26:32.852  - [32minfo[39m: ham.0 (25907) Terminated (NO_ERROR): Without reason
2020-04-29 08:26:33.375  - [32minfo[39m: host.iobroker instance system.adapter.ham.0 terminated with code 0 (NO_ERROR)
```
![image](https://user-images.githubusercontent.com/37106885/80563966-3d7fcd00-89f5-11ea-9398-62a9822cff7d.png)

**Comment by Apollon77** [comment]
You use homebridge 1.xor? The adapter do not support that as of now.

**Comment by Anzic23** [comment]
yes, 1.0.3. Ok, go back to 0.4.53

**Comment by Apollon77** [comment]
duplicate to #58

**Comment by Apollon77** [comment]
Please try with a homebridge 1.1 and the new 2.0 of the adapter

**Comment by Anzic23** [comment]
version 3.0.0 works good
