### ISSUE TITLE
Cyclic restart when there is no connection to the device.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.ham#68]
**Describe the bug**  
I noticed that the adapter restarts if the device from the plugin is not available. the homebridge-vera plugin is installed. it usually works fine. But now the VERA EDGE device (192.168.1.54) is not available (power loss). And the adapter is constantly rebooting because of this.
**To Reproduce**  
1. install homebridge-vera
2. power off vera device
3. See error

**Expected behavior**  
ignoring a device that is not online. Or an indication in homekit "no connection".

**Screenshots & Logfiles**  

```
2020-09-04 10:41:46.853  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Accessory-Information.Firmware-Revision
2020-09-04 10:41:46.853  - [32minfo[39m: ham.0 (376) stateChange ham.0.Playstation-4.Accessory-Information.Hardware-Revision {"val":"","ack":true,"ts":1599205306814,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1593114124180}
2020-09-04 10:41:46.854  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Accessory-Information.Hardware-Revision
2020-09-04 10:41:46.854  - [32minfo[39m: ham.0 (376) stateChange ham.0.Playstation-4.Accessory-Information.Software-Revision {"val":"","ack":true,"ts":1599205306814,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1596565653982}
2020-09-04 10:41:46.854  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Accessory-Information.Software-Revision
2020-09-04 10:41:46.854  - [32minfo[39m: ham.0 (376) stateChange ham.0.Playstation-4.Accessory-Information.Product-Data {"val":null,"ack":true,"ts":1599205306814,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1596565653982}
2020-09-04 10:41:46.854  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Accessory-Information.Product-Data
2020-09-04 10:41:46.854  - [32minfo[39m: ham.0 (376) stateChange ham.0.Playstation-4.Playstation-4.Name {"val":"Playstation 4","ack":true,"ts":1599205306814,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1599205306814}
2020-09-04 10:41:46.855  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Playstation-4.Name
2020-09-04 10:41:46.855  - [32minfo[39m: ham.0 (376) stateChange ham.0.Playstation-4.Playstation-4.Name {"val":"","ack":true,"ts":1599205306814,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1599205195730}
2020-09-04 10:41:46.855  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Playstation-4.Name
2020-09-04 10:41:46.855  - [32minfo[39m: ham.0 (376) stateChange ham.0.Playstation-4.Playstation-4.On {"val":false,"ack":true,"ts":1599205306823,"q":0,"from":"system.adapter.ham.0","user":"system.user.admin","lc":1598780315875}
2020-09-04 10:41:46.855  - [34mdebug[39m: ham.0 (376) lookup id: Playstation-4.Playstation-4.On
2020-09-04 10:41:49.210  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-09-04 10:41:49.211  - [31merror[39m: ham.0 (376) unhandled promise rejection: Error: connect EHOSTUNREACH 192.168.1.54:3480
2020-09-04 10:41:49.211  - [31merror[39m: ham.0 (376) RequestError: Error: connect EHOSTUNREACH 192.168.1.54:3480
    at new RequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/iobroker/node_modules/iobroker.ham/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-09-04 10:41:49.212  - [32minfo[39m: ham.0 (376) cleaned everything up...
2020-09-04 10:41:49.252  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-09-04 10:41:49.252  - [31merror[39m: ham.0 (376) unhandled promise rejection: Error: connect EHOSTUNREACH 192.168.1.54:3480
2020-09-04 10:41:49.252  - [31merror[39m: ham.0 (376) RequestError: Error: connect EHOSTUNREACH 192.168.1.54:3480
    at new RequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/iobroker/node_modules/iobroker.ham/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-09-04 10:41:49.253  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-09-04 10:41:49.253  - [31merror[39m: ham.0 (376) unhandled promise rejection: Error: connect EHOSTUNREACH 192.168.1.54:3480
2020-09-04 10:41:49.253  - [31merror[39m: ham.0 (376) RequestError: Error: connect EHOSTUNREACH 192.168.1.54:3480
    at new RequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/iobroker.ham/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/iobroker/node_modules/iobroker.ham/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/opt/iobroker/node_modules/iobroker.ham/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-09-04 10:41:49.275  - [32minfo[39m: ham.0 (376) terminating
2020-09-04 10:41:49.277  - [32minfo[39m: ham.0 (376) Terminated (NO_ERROR): Without reason
2020-09-04 10:41:49.849  - [31merror[39m: host.iobroker Caught by controller[0]: [9/4/2020, 10:41:45 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-cmdswitch2' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-cmdswitch2'.
2020-09-04 10:41:49.850  - [31merror[39m: host.iobroker Caught by controller[1]: [9/4/2020, 10:41:45 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-gree-heatercooler' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-gree-heatercooler'.
2020-09-04 10:41:49.850  - [31merror[39m: host.iobroker Caught by controller[2]: [9/4/2020, 10:41:45 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-mi-hygrothermograph' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-mi-hygrothermograph'.
2020-09-04 10:41:49.850  - [31merror[39m: host.iobroker Caught by controller[3]: [9/4/2020, 10:41:45 AM] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
2020-09-04 10:41:49.850  - [31merror[39m: host.iobroker Caught by controller[4]: [9/4/2020, 10:41:45 AM] Warning: skipping plugin found at '/opt/iobroker/node_modules/homebridge-vera' since we already loaded the same plugin from '/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-vera'.
2020-09-04 10:41:49.851  - [31merror[39m: host.iobroker Caught by controller[5]: [9/4/2020, 10:41:45 AM] ====================
2020-09-04 10:41:49.851  - [31merror[39m: host.iobroker Caught by controller[6]: [9/4/2020, 10:41:45 AM] ERROR INITIALIZING PLUGIN homebridge-mi-hygrothermograph:
2020-09-04 10:41:49.851  - [31merror[39m: host.iobroker Caught by controller[7]: [9/4/2020, 10:41:45 AM] Error: EAFNOSUPPORT, Address family not supported by protocol
2020-09-04 10:41:49.851  - [31merror[39m: host.iobroker Caught by controller[7]:     at new Hci (/opt/iobroker/node_modules/iobroker.ham/node_modules/@abandonware/noble/lib/hci-socket/hci.js:74:18)
2020-09-04 10:41:49.851  - [31merror[39m: host.iobroker Caught by controller[7]:     at new NobleBindings (/opt/iobroker/node_modules/iobroker.ham/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
2020-09-04 10:41:49.852  - [31merror[39m: host.iobroker Caught by controller[7]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ham/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:546:18)
2020-09-04 10:41:49.852  - [31merror[39m: host.iobroker Caught by controller[7]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2020-09-04 10:41:49.852  - [31merror[39m: host.iobroker Caught by controller[7]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-09-04 10:41:49.852  - [31merror[39m: host.iobroker Caught by controller[7]:     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-09-04 10:41:49.852  - [31merror[39m: host.iobroker Caught by controller[7]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-09-04 10:41:49.852  - [31merror[39m: host.iobroker Caught by controller[7]:     at Function.Module._load (/opt/iobroker/node_modules/mock-require/index.js:30:22)
2020-09-04 10:41:49.853  - [31merror[39m: host.iobroker Caught by controller[7]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
2020-09-04 10:41:49.853  - [31merror[39m: host.iobroker Caught by controller[7]:     at require (internal/modules/cjs/helpers.js:72:18)
2020-09-04 10:41:49.853  - [31merror[39m: host.iobroker Caught by controller[8]: [9/4/2020, 10:41:45 AM] ====================
2020-09-04 10:41:49.853  - [32minfo[39m: host.iobroker instance system.adapter.ham.0 terminated with code 0 (NO_ERROR)
2020-09-04 10:41:49.853  - [32minfo[39m: host.iobroker Restart adapter system.adapter.ham.0 because enabled
```
**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 3.1.6
 - Node version: v12.18.3
 - Operating system: docker

**Comment by Apollon77** [comment]
It seems to be that the Plugin you use is not catching the errors, so the adapter also can not fo it. It would be the same ith a stand alone homebridge.

Please open issue with the relevant plugin

**Comment by Apollon77** [comment]
PS: here you go I would assume, or ?! https://github.com/damianxd/homebridge-vera/issues/176
